### PR TITLE
Fix NPE for all list based api calls for compute

### LINKED ISSUE #93: GCP: Fix NPE for all list based api calls for compute
A recent API change on GCP end, results in NPE when a list based api is called and there is no items present. The root cause being that the response previously returned an empty list, but now returns a null.

### PR DESCRIPTION
**Pull request by deepanjan90**
Fixes #93 

All places under the compute resource where a list based call is made, there is a possibility of NPE if no resource is present of that type.

Previously the api would return an empty list in the `items` if none was found, but now it returns null which causes the NPE.

### CODE REVIEW

File: src/main/java/gyro/google/compute/InstanceFinder.java [hunk 1]
```diff
@@ -70,10 +71,10 @@ public void setFilter(String filter) {
     protected List<Instance> findAllGoogle(Compute client) throws Exception {
         List<Instance> instances = new ArrayList<>();
         String pageToken;
-        List<String> zones = client.zones().list(getProjectId()).execute().getItems()
-            .stream()
-            .map(Zone::getName)
-            .collect(Collectors.toList());
+        List<Zone> zoneList = Optional.ofNullable(client.zones().list(getProjectId()).execute().getItems()).orElse(new ArrayList<>());
```
Comment (alex-lambrides) [inline src/main/java/gyro/google/compute/InstanceFinder.java]: This line exceeds the line max character count.

File: src/main/java/gyro/google/compute/InstanceFinder.java [hunk 2]
```diff
@@ -70,10 +71,10 @@ public void setFilter(String filter) {
...
+        List<String> zones = zoneList.stream()
+                .map(Zone::getName)
+                .collect(Collectors.toList());
```
Comment (alex-lambrides) [inline src/main/java/gyro/google/compute/InstanceFinder.java]: These should only be indented 4 rather than 8 spaces.

File: src/main/java/gyro/google/compute/ProjectMetadataItemFinder.java [hunk 3]
```diff
@@ -53,20 +56,26 @@ public void setKey(String key) {
 
     @Override
     protected List<Metadata.Items> findAllGoogle(Compute client) throws Exception {
-        return client.projects().get(getProjectId()).execute().getCommonInstanceMetadata().getItems();
+        return Optional.ofNullable(client.projects().get(getProjectId()).execute().getCommonInstanceMetadata().getItems()).orElse(new ArrayList<>());
```
Comment (alex-lambrides) [inline src/main/java/gyro/google/compute/ProjectMetadataItemFinder.java]: This line exceeds the line max character count.
